### ISSUE TITLE
Group By

### ISSUE THREAD

**Issue by schickling** [prisma/photonjs#1]
## Problem

Most database support ways to indicate how to group results, especially in combination with usage of aggregators.
Prisma 2 currently doesn't offer any way to group results, and requires to fall back to using raw SQL queries. This defeats the benefits of having a type-safe client, and hurts code maintainability.

## Suggested solution

Add support for ways to group results

**Initial API example proposal:**

```ts
type DynamicResult4 = {
  lastName: string
  records: User[]
  aggregate: { age: { avg: number } }
}
const groupByResult: DynamicResult4 = await prisma.users.groupBy({
  key: 'lastName',
  having: { age: { avgGt: 10 } },
  where: { isActive: true },
  first: 100,
  orderBy: { lastName: 'ASC' },
  select: {
    records: { take: 100 },
    aggregate: { age: { avg: true } },
  },
})

type DynamicResult5 = {
  raw: any
  records: User[]
  aggregate: { age: { avg: number } }
}
const groupByResult2: DynamicResult5 = await prisma.users.groupBy({
  raw: { key: 'firstName || lastName', having: 'AVG(age) > 50' },
  select: {
    records: { $first: 100 },
    aggregate: { age: { avg: true } },
  },
})
```

## Next steps

 - [ ] Define scope of the kinds of group by statement we want to support first
 - [ ] Agree on API design
 - [ ] Implement in engines
 - [ ] Implement in client

**Comment by ryancwalsh** [comment]
I'm subscribing to this issue because I'm looking forward to this `groupBy` functionality! I'd love to be able to use `groupBy` and `count` like [this](https://stackoverflow.com/q/61583375/470749).

Especially because—given that I [can't use params](https://github.com/prisma/prisma/issues/1929#issuecomment-623745540) with `raw`—I apparently can't yet accomplish what I'm trying to do, even though it's probably a basic use case.

**Comment by divideby0** [comment]
Now that we have aggregations in Prisma 2.3.0 (#2838), is this groupBy functionality getting a second look? I personally think it would be a huge win to enable it for lightweight faceted search/filtering without introducing something like Algolia or Elasticsearch into the fold. Right now, I'm exploring Knex combined with `queryRaw` for this: http://knexjs.org/#Builder-groupBy, but it'd be nice to have something that provided more type safety to the model.

**Comment by matthewmueller** [comment]
We're starting to design this API now.  

We'd really appreciate some examples of the types of queries you'd like to support 🙏

**Comment by ryancwalsh** [comment]
Thanks, @matthewmueller. My desired use case is above: https://github.com/prisma/prisma-client-js/issues/1#issuecomment-633576224

**Comment by hayes** [comment]
Would be awesome if this supported grouping by multiple columns and selecting multiple aggregates of the same column, eg:

```ts
await prisma.results.aggregate({
      where: {
        userId: this.user.id,
      },
      avg: {
        score: true,
      },
      max: {
        score: true,
      },
      groupBy: ['map', 'mode']
    });
```
would return something like:
```json
[
  { map: 1, mode 1, max: { score: 10 } avg: { score: 5 } },
  { map: 1, mode 2 max: { score: 8 } avg: { score: 3 } },
]
```

**Comment by hayes** [comment]
The above might run into naming collisions though, so maybe rather than `score: true`, it should be something like `score: maxScore` to create an alias for the aggregate.

**Comment by matthewmueller** [comment]
@hayes that's an interesting idea, what would the SQL look like in this case?

**Comment by hayes** [comment]
`SELECT map, mode, max(score) as max score, avg(score) as avg score from results where id = 123 group by map, mode; `

**Comment by hayes** [comment]
The actual query this was based on also has a limit and an order by on one of the aggregates, haven't really thought through how the order by might affect the API

**Comment by matthewmueller** [comment]
Thanks! Actually, do you mind sharing the whole query? We may not be able to cover it fully from an API perspective for V1, but it would be nice to try!

**Comment by hayes** [comment]
`SELECT map, mode, max(score) as maxScore, avg(score) as avgScore from results where id = 123 group by map, mode order by maxScore limit 10;`

**Comment by P4sca1** [comment]
> We'd really appreciate some examples of the types of queries you'd like to support 🙏
I would like to be able to group by date time functions: https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_month
e.g. for a query that returns the monthly income per month and year:
```sql
SELECT SUM(price) AS 'totalIncome', YEAR(createdAt) AS 'year', MONTH(createdAt) AS 'month' FROM payments GROUP BY YEAR(createdAt), MONTH(createdAt)
```

**Comment by blakeley** [comment]
> We'd really appreciate some examples of the types of queries you'd like to support 🙏

I'm developing a social app where people can favorite other user's creations, and I'd like to be able to query these creations ordered by "most favorited". So something like:
```typescript
 await prisma.thing.findMany({
    orderBy: {
      favorites: 'count'
    },
    include: {
      createdBy: {
        select: {
          name: true,
        },
      },
      favorites: {
        select: { thingId: true },
      },
    },
  });
```

**Comment by Sytten** [comment]
The proposed syntax with a new operator seems weird since this won't allow for an outer findFirst/findMany with an inner groupBy query.

**Comment by matthewmueller** [comment]
Thanks @blakeley for the suggestion! 

@Sytten which new operator do you mean?

### Updated Proposal

**Given:**

```sql
SELECT DeptID, SUM(SaleAmount) 
FROM Sales 
WHERE SaleDate = '01-Jan-2000' 
GROUP BY DeptID 
HAVING SUM(SaleAmount) > 1000
```

**TS API:**

```ts
const out: any = prisma.sales.aggregate({
  select: {
    deptId: true 
  },
  sum: {
    saleAmount: true
  },
  where: { 
    saleDate: '01-Jan-2000'
  },
  having: {
    sum: {
      saleAmount: { 
        gt: 1000 
      }
    }
  },
  groupBy: { 
    deptId: true 
  }
})
```

### Steps

#### Step 1: Add `groupBy` field to `aggregate()`

- `groupBy` can only have fields (e.g. deptId or email), no aggregations (e.g. sum or avg).
- `groupBy` is useful without `having`
    - e.g. `SELECT DeptID FROM Sales GROUP BY DeptID`
- `groupBy` with multiple fields is out of scope, unless it turns out to be easy to add during implementation.
    - Our API is ready to support this later: `groupBy: { deptId: true, saleDate: true }`
- Should work with our other `aggregate()` features like where, limit, orderBy

#### Step 2: Add `select` field to `aggregate()`

- `select` can only have fields (e.g. `deptId` or `email`), no aggregations (e.g. `sum` or `avg`).
- Selecting on aggregations is done in the `aggregate` object, not in the `select` object
    - Supported aggregates: `avg`, `sum`, `min`, `max`. We already support these in aggregate().
    - We acknowledge this is a bit confusing, but the existing aggregate API does it this way.
- `select` should work without `groupBy` or `having`
- Should work with our other `aggregate()` features like where, limit, orderBy

#### Step 3: Add `having` field to `aggregate()`

- `having` can only refer to columns of the `select` OR be an aggregation.
    - e.g. `SELECT DeptID FROM Sales GROUP BY DeptID having DeptID > 10 and sum(saleAmount)`
- `having` can only occur when you have `groupBy`
- `where` and `having` together should be possible.
    - Conceptually, `having` is a filter applied after the results are grouped. `where` filters the results before they're grouped.
- Should work with our other `aggregate()` features like where, limit, orderBy

### Limitations

Right now we're planning on adding group by support to `.aggregate()` rather than `findFirst`, `findMany`. This may change in the future, but it's a reasonable starting point to enable group by having. 

Another caveat is that the output won't be type-safe. We'd like to get this feature into your hands as soon as possible. This limitation may change over time, but our protocol isn't set up for this yet and many use cases of group by are about viewing the returned data, rather than acting upon it. This is a limitation that may be fixed in a future iteration.

---

If you have any thoughts on the proposal, please let us know!

**Comment by Sytten** [comment]
Nvm I just read the initial proposal at the top and didnt bother checking after, I like the syntax of your example. Except I think groupBy shoulds be an array like orderBy.

**Comment by matthewmueller** [comment]
Good catch! `groupBy` order does matter on some databases, so it should be an array. I've updated the proposal above.

**Comment by zackify** [comment]
I want to do a simple group by on a table to get the count of items.

Ex: posts table, and each row has a categoryId

I want to grab the count of all posts, grouped by the category id, so that I can see how many posts are in each category.

**Comment by timsuchanek** [comment]
This has been implemented in the latest `@prisma/client@dev` version and will be released in preview today.
You can check it out with setting "groupBy" as a previewFeature in your `schema.prisma`.
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["groupBy"]
}
```
It is then available on `prisma.user.groupBy`.
You can check out some examples in our tests: https://github.com/prisma/prisma/blob/master/src/packages/client/src/__tests__/integration/happy/groupBy/test.ts
More details on how to use it are following in docs and release notes today.
